import {readFileSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {filterProjectChatOptions,projectChatSelection,emptyAdminProjectThread,retainOpenProjectThreads} from '@/lib/message-workspace';
import {demoProjects} from '@/lib/demo-data';
const projects=[{...demoProjects[0],id:'10000000-0000-4000-8000-000000000001',clientName:'Eric Wilson',projectName:'Buyer Follow-up',status:'active' as const}];
describe('project chat selector',()=>{
 it('filters client and project names case-insensitively without changing source',()=>{expect(filterProjectChatOptions(projects,' ERIC ')).toEqual(projects);expect(filterProjectChatOptions(projects,'buyer')).toEqual(projects);expect(filterProjectChatOptions(projects,'missing')).toEqual([]);expect(filterProjectChatOptions(projects,'')).toEqual(projects)});
 it('rejects clients, unknown projects and inactive projects',()=>{expect(projectChatSelection('client',projects,[],projects[0].id)).toBeNull();expect(projectChatSelection('admin',projects,[],'foreign')).toBeNull();expect(projectChatSelection('admin',[{...projects[0],status:'completed'}],[],projects[0].id)).toBeNull()});
 it('reuses an existing project conversation rather than the task thread',()=>{const thread=emptyAdminProjectThread(projects[0]);expect(projectChatSelection('admin',projects,[{...thread,kind:'task',key:'task:'+projects[0].id},thread],projects[0].id)).toBe(thread)});
 it('opens an empty project thread and retains it until the inventory contains it',()=>{const thread=projectChatSelection('admin',projects,[],projects[0].id)!;expect(thread).toMatchObject({kind:'project',key:'project:'+projects[0].id,preview:null,unreadCount:0});const previous={projects,threads:[thread]};expect(retainOpenProjectThreads({projects,threads:[]},previous).threads).toEqual([thread]);const populated={...thread,preview:'First message'};expect(retainOpenProjectThreads({projects,threads:[populated]},previous).threads).toEqual([populated])});
 it('uses local filtering and existing encoded deep links without new fetches',()=>{const source=readFileSync('components/messages-workspace.tsx','utf8');expect(source).toContain('Search client or project');expect(source).toContain('encodeURIComponent(key)');expect(source).toContain("role === 'admin' && projectPicker");expect(source).not.toContain('fetch(');expect(source).not.toContain('router.refresh')});
});
describe('template title migration',()=>{
 it('changes only the insertion title expression in the prior function body',()=>{const prior=readFileSync('supabase/migrations/202608270001_single_lead_workflow.sql','utf8').replaceAll('\r','');const start=prior.indexOf('create or replace function public.import_template_tasks(');const body=prior.slice(start,prior.indexOf('create or replace function public.complete_project_task')).split('as $$')[1].split('$$;')[0].trim();const migration=readFileSync('supabase/migrations/202610050001_preserve_imported_template_title.sql','utf8').replaceAll('\r','');const next=migration.split('AS $function$')[1].split('$function$')[0].trim();expect(next).toBe(body.replace("template_task_row.title || ' - ' || primary_client_name",'template_task_row.title'));expect(migration).not.toMatch(/update public.project_tasks/i)});
 it('leaves editable stored titles and manual title writes intact',()=>{const editor=readFileSync('components/admin/task-editor.tsx','utf8');expect(editor).toContain('useState(task.title)');expect(editor).toContain('JSON.stringify({ title,');expect(editor).toContain('setTitle(');const route=readFileSync('app/api/admin/tasks/[taskId]/route.ts','utf8');expect(route).toContain('title: parsed.data.title')});
});
