import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, CalendarBlank, FolderOpen, PaperPlaneTilt } from '@phosphor-icons/react/dist/ssr';
import { requireRole } from '@/lib/auth';
import { formatDate } from '@/lib/format';
import { getPersonActivity, getPersonBase, getPersonEmails, getPersonForms, getPersonOverview, getPersonProjects, PERSON_TAB_PAGE_SIZE } from '@/lib/people';
import { PersonProfileHeader } from '@/components/admin/person-profile-client';
import { EmailHistory } from '@/components/admin/email-history';
import { InviteButton } from '@/components/admin/invite-button';

const validTabs = new Set(['overview', 'projects', 'forms', 'emails', 'activity']);

export default async function PersonPage({ params, searchParams }: { params: Promise<{ clientId: string }>; searchParams: Promise<{ tab?: string; page?: string; filter?: string }> }) {
  const [{ clientId }, query] = await Promise.all([params, searchParams]);
  const tab = validTabs.has(query.tab || '') ? query.tab! : 'overview';
  const page = Math.max(1, Number.parseInt(query.page || '1', 10) || 1);
  const filter = ['all', 'assignments', 'feedback', 'meetings', 'invitations'].includes(query.filter || '') ? query.filter! : 'all';
  const [, person] = await Promise.all([requireRole('admin'), getPersonBase(clientId)]);
  if (!person) notFound();
  const content = tab === 'overview' ? await getPersonOverview(clientId) : tab === 'projects' ? await getPersonProjects(clientId) : tab === 'forms' ? await getPersonForms(clientId, page) : tab === 'emails' ? await getPersonEmails(clientId, page, filter) : await getPersonActivity(clientId, page);
  return <div className="page-wrap"><Link prefetch={false} href="/admin/people" className="mb-5 inline-flex items-center gap-1 text-xs font-semibold text-muted hover:text-ink">← All People</Link><PersonProfileHeader person={person} activeTab={tab} /><section className="surface-flat overflow-hidden rounded-t-none">{tab === 'overview' && <Overview person={person} data={content as Awaited<ReturnType<typeof getPersonOverview>>} />}{tab === 'projects' && <Projects rows={content as Awaited<ReturnType<typeof getPersonProjects>>} />}{tab === 'forms' && <Forms clientId={clientId} page={page} result={content as Awaited<ReturnType<typeof getPersonForms>>} />}{tab === 'emails' && <Emails clientId={clientId} page={page} filter={filter} result={content as Awaited<ReturnType<typeof getPersonEmails>>} />}{tab === 'activity' && <Activity clientId={clientId} page={page} result={content as Awaited<ReturnType<typeof getPersonActivity>>} />}</section></div>;
}

function Overview({ person, data }: { person: NonNullable<Awaited<ReturnType<typeof getPersonBase>>>; data: Awaited<ReturnType<typeof getPersonOverview>> }) { if (!data) return null; return <div className="p-5 sm:p-7"><h2 className="text-lg font-bold">Client details</h2><div className="mt-5 grid gap-x-10 gap-y-4 text-sm sm:grid-cols-2"><Detail label="Client" value={person.fullName} /><Detail label="Email" value={person.email} /><Detail label="Company" value={person.company || '—'} /><Detail label="Title" value={person.title || '—'} /><Detail label="Phone" value={person.phone || '—'} /><Detail label="Added" value={formatDate(person.createdAt)} /><Detail label="Last login" value={person.lastLoginAt ? formatDate(person.lastLoginAt) : 'Never'} /><Detail label="Portal access" value={person.status} /></div><h2 className="mt-9 text-lg font-bold">Summary</h2><div className="metric-strip mt-4"><Metric label="Projects" value={data.projectCount} /><Metric label="Leads assigned" value={data.totalLeads} /><Metric label="Active" value={data.activeLeads} /><Metric label="Completed" value={data.completedLeads} /><Metric label="Feedback pending" value={data.feedbackPending} /><Metric label="Feedback submitted" value={data.feedbackSubmitted} /></div>{data.upcomingMeeting && <Link prefetch={false} href={`/admin/meetings/${data.upcomingMeeting.id}`} className="mt-5 flex items-center gap-3 rounded-lg border border-line bg-surface-subtle p-4"><CalendarBlank size={20} className="text-brand-text" /><div><p className="text-xs font-semibold text-muted">Upcoming meeting</p><p className="mt-1 text-sm font-bold">{data.upcomingMeeting.title} · {formatDate(data.upcomingMeeting.start_at)}</p></div><ArrowRight className="ml-auto" size={16} /></Link>}{data.firstProjectId && <div className="mt-7 max-w-xs"><InviteButton projectId={data.firstProjectId} /></div>}</div>; }
function Projects({ rows }: { rows: Awaited<ReturnType<typeof getPersonProjects>> }) { return <><Header title="Projects" copy="Only projects connected through this person's project membership." /><div className="overflow-x-auto"><table className="data-table min-w-[760px]"><thead><tr><th>Project</th><th>Owner</th><th>Status</th><th>Created</th><th>Lead count</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.project!.id}><td className="font-semibold">{row.project!.project_name}</td><td>{projectOwnerName(row.project!.owner)}</td><td className="capitalize">{row.project!.status}</td><td>{formatDate(row.project!.created_at)}</td><td>{(row.project!.project_tasks || []).filter((task) => !task.archived_at).length}</td><td><Link prefetch={false} className="button-secondary" href={`/admin/projects/${row.project!.id}`}><FolderOpen size={15} />Open project</Link></td></tr>)}</tbody></table></div>{!rows.length && <Empty text="No projects are attached to this person." />}</>; }
function Forms({ clientId, page, result }: { clientId: string; page: number; result: Awaited<ReturnType<typeof getPersonForms>> }) { return <><Header title="Forms" copy="Lead Assignment feedback and form history from the existing task workflow." /><div className="overflow-x-auto"><table className="data-table min-w-[900px]"><thead><tr><th>Lead / Task</th><th>Form type</th><th>Status</th><th>Requested</th><th>Submitted</th><th>Rating</th><th>Actions</th></tr></thead><tbody>{result.rows.map((row) => { const submission = row.form_submissions?.[0]; const rating = submission && typeof submission.answers === 'object' ? Object.values(submission.answers as Record<string, unknown>).find((value) => typeof value === 'number' || (typeof value === 'string' && /^\d+(\.\d+)?$/.test(value))) : null; return <tr key={row.id}><td><p className="font-semibold">{row.title}</p><p className="text-xs text-muted">{row.project?.project_name}</p></td><td>{row.task_type === 'form' ? 'Form' : 'Feedback'}</td><td className="capitalize">{row.feedback_state === 'not_configured' ? 'Not requested' : row.feedback_state}</td><td>{formatDate(row.feedback_requested_at || row.feedback_scheduled_for)}</td><td>{formatDate(row.feedback_submitted_at || submission?.submitted_at || null)}</td><td>{rating ? String(rating) : '—'}</td><td><Link prefetch={false} className="button-secondary" href={`/admin/projects/${row.project?.id}/tasks/${row.id}`}>Open</Link></td></tr>; })}</tbody></table></div>{!result.rows.length && <Empty text="No forms or feedback requests are associated with this person." />}<Pager clientId={clientId} tab="forms" page={page} total={result.total} /></>; }
function Emails({ clientId, page, filter, result }: { clientId: string; page: number; filter: string; result: Awaited<ReturnType<typeof getPersonEmails>> }) { return <><div className="flex flex-col gap-4 border-b border-line p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold">Email history</h2><p className="mt-1 text-sm text-muted">Stored transactional records only; no secure link content is exposed.</p></div><div className="flex flex-wrap gap-1">{['all','assignments','feedback','meetings','invitations'].map((item) => <Link prefetch={false} key={item} className={`rounded-md px-3 py-2 text-xs font-semibold capitalize ${filter === item ? 'bg-brand-soft text-brand-text' : 'text-muted hover:bg-brand-soft'}`} href={`/admin/people/${clientId}?tab=emails&filter=${item}`}>{item}</Link>)}</div></div><EmailHistory rows={result.rows} />{!result.rows.length && <Empty text="No stored emails match this filter." />}<Pager clientId={clientId} tab="emails" page={page} total={result.total} extra={`&filter=${filter}`} /></>; }
function Activity({ clientId, page, result }: { clientId: string; page: number; result: Awaited<ReturnType<typeof getPersonActivity>> }) { return <><Header title="Lead Assignment activity" copy="Complete assignment history for this realtor, newest first." /><div className="space-y-3 p-5 sm:p-7">{result.rows.map((row) => <article key={row.id} className="rounded-lg border border-line bg-surface-subtle p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 flex-none place-items-center rounded-full bg-brand-soft text-brand-text"><PaperPlaneTilt size={17} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-bold">Lead assigned to this realtor</p><time className="text-xs text-muted">{formatDate(row.activated_at || row.created_at)}</time></div><Link prefetch={false} href={`/admin/projects/${row.project?.id}/tasks/${row.id}`} className="mt-2 inline-flex items-center gap-1 font-semibold text-brand-text hover:underline">{row.title}<ArrowRight size={13} /></Link><p className="mt-1 text-xs capitalize text-muted">{row.project?.project_name} · {row.status} · Feedback {row.feedback_state.replaceAll('_', ' ')}</p></div></div></article>)}</div>{!result.rows.length && <Empty text="No Lead Assignments are associated with this person." />}<Pager clientId={clientId} tab="activity" page={page} total={result.total} /></>; }
function Header({ title, copy }: { title: string; copy: string }) { return <div className="border-b border-line p-5 sm:p-7"><h2 className="text-lg font-bold">{title}</h2><p className="mt-1 text-sm text-muted">{copy}</p></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="grid grid-cols-[110px_1fr] gap-3"><p className="text-muted">{label}</p><p className="font-semibold capitalize">{value}</p></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="metric-item"><p className="metric-label">{label}</p><p className="metric-value">{value}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="p-12 text-center text-sm text-muted">{text}</div>; }
function Pager({ clientId, tab, page, total, extra = '' }: { clientId: string; tab: string; page: number; total: number; extra?: string }) { const pages = Math.ceil(total / PERSON_TAB_PAGE_SIZE); if (pages <= 1) return null; return <div className="flex justify-end gap-2 border-t border-line p-4">{page > 1 && <Link prefetch={false} className="button-secondary" href={`/admin/people/${clientId}?tab=${tab}&page=${page - 1}${extra}`}>Previous</Link>}{page < pages && <Link prefetch={false} className="button-secondary" href={`/admin/people/${clientId}?tab=${tab}&page=${page + 1}${extra}`}>Next</Link>}</div>; }
function projectOwnerName(owner: unknown) { const value = Array.isArray(owner) ? owner[0] : owner; return value && typeof value === 'object' && 'full_name' in value ? String(value.full_name) : '—'; }
