'use client';

import { useEffect, useRef } from 'react';
import { LinkSimple, ListBullets, ListNumbers, TextB, TextH, TextItalic } from '@phosphor-icons/react';

export function RichTextEditor({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const editor = useRef<HTMLDivElement>(null);
  useEffect(() => { if (editor.current && editor.current.innerHTML !== value) editor.current.innerHTML = value; }, [value]);
  function command(name: string, argument?: string) { document.execCommand(name, false, argument); editor.current?.focus(); onChange(editor.current?.innerHTML || ''); }
  return <div className="overflow-hidden rounded-lg border border-line-strong focus-within:border-brand focus-within:ring-4 focus-within:ring-focus"><div className="flex flex-wrap gap-1 border-b border-line bg-surface-subtle p-2"><button type="button" aria-label="Heading" title="Heading" className="button-ghost h-8 px-2" onClick={() => command('formatBlock', 'h2')}><TextH size={16} aria-hidden /></button><button type="button" aria-label="Bold" title="Bold" className="button-ghost h-8 px-2" onClick={() => command('bold')}><TextB size={16} weight="bold" aria-hidden /></button><button type="button" aria-label="Italic" title="Italic" className="button-ghost h-8 px-2" onClick={() => command('italic')}><TextItalic size={16} aria-hidden /></button><button type="button" aria-label="Bulleted list" title="Bulleted list" className="button-ghost h-8 px-2" onClick={() => command('insertUnorderedList')}><ListBullets size={16} aria-hidden /></button><button type="button" aria-label="Numbered list" title="Numbered list" className="button-ghost h-8 px-2" onClick={() => command('insertOrderedList')}><ListNumbers size={16} aria-hidden /></button><button type="button" aria-label="Insert link" title="Insert link" className="button-ghost h-8 px-2" onClick={() => { const url = window.prompt('Link URL'); if (url) command('createLink', url); }}><LinkSimple size={16} aria-hidden /></button></div><div ref={editor} contentEditable suppressContentEditableWarning role="textbox" aria-multiline="true" className="task-rich-text min-h-48 p-4 outline-none" onInput={(event) => onChange(event.currentTarget.innerHTML)} /></div>;
}
