'use client';

import { useState } from 'react';
import { Eye, X } from '@phosphor-icons/react';
import { formatDate } from '@/lib/format';

type EmailRow = { id: string; email_type: string; recipient_email: string | null; template_data: Record<string, unknown>; status: string; last_error: string | null; created_at: string; sent_at: string | null; project: { id: string; project_name: string } | null; task: { id: string; title: string } | null };
const labels: Record<string, string> = { 'task.assigned': 'Lead Assignment', 'feedback.requested': 'Feedback request', 'feedback.submitted': 'Feedback submitted', 'meeting.booked': 'Meeting booked', 'meeting.cancelled': 'Meeting cancelled', 'meeting.reminder': 'Meeting reminder', client_invitation: 'Portal invitation', client_sign_in: 'Sign-in link' };
function subject(row: EmailRow) { const stored = typeof row.template_data?.subject === 'string' ? row.template_data.subject : null; if (stored) return stored; const project = row.project?.project_name || 'your project'; if (row.email_type === 'task.assigned') return `You've been assigned ${row.task?.title || 'a Lead Assignment'} in ${project}`; if (row.email_type === 'feedback.requested') return `Feedback requested for ${row.task?.title || project}`; if (row.email_type === 'feedback.submitted') return `Feedback submitted for ${row.task?.title || project}`; if (row.email_type === 'client_invitation') return `Your invitation to ${project}`; return `${labels[row.email_type] || 'Transactional email'} — ${project}`; }
export function EmailHistory({ rows }: { rows: EmailRow[] }) { const [selected, setSelected] = useState<EmailRow | null>(null); return <><div className="overflow-x-auto"><table className="data-table min-w-[820px]"><thead><tr><th>Date</th><th>Type</th><th>Subject</th><th>Project</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.id}-${row.email_type}`}><td className="text-muted">{formatDate(row.sent_at || row.created_at)}</td><td>{labels[row.email_type] || row.email_type}</td><td className="max-w-md">{subject(row)}</td><td>{row.project?.project_name || '—'}</td><td><span className={`status-badge ${row.status === 'failed' ? 'status-cancelled' : row.status === 'sent' ? 'status-completed' : 'status-active'}`}>{row.status}</span></td><td><button className="icon-button" aria-label="View email details" onClick={() => setSelected(row)}><Eye size={17} /></button></td></tr>)}</tbody></table></div>{selected && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Email details"><div className="modal-card"><div className="flex items-start justify-between"><div><p className="page-eyebrow">Safe email record</p><h2 className="text-xl font-bold">{subject(selected)}</h2></div><button className="icon-button" onClick={() => setSelected(null)} aria-label="Close"><X size={18} /></button></div><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><Detail label="To" value={selected.recipient_email || 'Not retained in this delivery record'} /><Detail label="Type" value={labels[selected.email_type] || selected.email_type} /><Detail label="Date" value={formatDate(selected.sent_at || selected.created_at)} /><Detail label="Status" value={selected.status} /><Detail label="Project" value={selected.project?.project_name || '—'} /><Detail label="Lead Assignment" value={selected.task?.title || '—'} /></dl><p className="mt-6 rounded-lg bg-[#f2f5f4] p-4 text-xs leading-5 text-muted">Historical message bodies were not persisted. Secure links, TokenHash values, and authentication credentials are intentionally never reconstructed or exposed here.</p>{selected.last_error && <p className="mt-3 rounded-lg bg-[#fff1ef] p-3 text-sm text-[#934339]">{selected.last_error}</p>}</div></div>}</>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
